# Site settings
title: Perky Team
email: olga.sukhareva@perky.team
# url: https://github.com/jeromelachaud/freelancer-theme
description: "We're hiring Frontend Team Lead (JS, React), Senior Mobile Apps QA Engineer, Android Platform Lead/Android, iOS Developer"
keywords: "it-recruitment,it-recruiter,developer,manager,c++,golang,nodejs,android,ios"
skills: "IT Recruitment"
meta_author: Olga Sukhareva

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Build settings
markdown: kramdown
permalink: pretty
